### ISSUE TITLE
mpu9250

### ISSUE THREAD

**Issue by froussel** [PepeTheFroggie/EspCopter32#3]
Hello,

The mpu9250 has a 6050 also with magnetic data

Would it be possible to adapt the existing code EspCopter32 for the mpu9250 with the addition of a tilt compensated compass output ?

**Comment by PepeTheFroggie** [comment]
Yes

**Comment by froussel** [comment]
And can you make a exemple please ?

**Comment by PepeTheFroggie** [comment]
No

**Comment by froussel** [comment]
:-(
